---
- import_playbook: terminal_full.yml

- name: Configure desktop (full)
  hosts: all
  become: true

  roles:
    - odem.desktop.x11
    - odem.desktop.wm
    - odem.desktop.qtile
    - odem.desktop.rofi
    - odem.desktop.thunar
    - odem.desktop.essentials
    - odem.desktop.kanata
    - odem.desktop.lightdm
    - odem.desktop.plymouth
    - odem.desktop.grubmenu
    - odem.desktop.gnometools
    - odem.desktop.firefox
    - odem.desktop.thunderbird
    - odem.desktop.brave
    - odem.desktop.spotify
