---
- name: Testing hosts
  hosts: all
  become: true

  vars:
    lockdown_enable_execute: true

  roles:
    - odem.terminal.vim
    - odem.terminal.nvim
    - odem.terminal.bash
    - odem.terminal.scripts
