---
- import_playbook: desktop_full.yml

- name: Configure workstation (full)
  hosts: all
  become: true

  roles:
    # mps.optimize
    - mps.optimize.zram
    - mps.optimize.ramdisks
    - mps.optimize.kmscon

    # mps.development
    - mps.development.opencode
    - mps.development.java
    - mps.development.dotnet
    - mps.development.espidf
    - mps.development.latex
    - mps.development.lmstudio
    - mps.development.unity

    # mps.hardening
    - mps.hardening.firewall
    - mps.hardening.apparmor
    - mps.hardening.auditd
    - mps.hardening.aide
    - mps.hardening.lockdown
