---
- import_playbook: desktop_full.yml

- name: Configure workstation (minimal)
  hosts: all
  become: true

  roles:
    # odem.optimize
    - odem.optimize.zram
    - odem.optimize.ramdisks
    - odem.optimize.kmscon

    # odem.development
    - odem.development.opencode

    # odem.hardening
    - odem.hardening.firewall
    - odem.hardening.apparmor
    - odem.hardening.auditd
    - odem.hardening.aide
    - odem.hardening.lockdown
